name: local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: classId
    value: ''
  - key: userId
    value: ''
  - key: inviteToken
    value: ''
  - key: channelId
    value: ''
  - key: messageId
    value: ''
  - key: channelAttachmentId
    value: ''
  - key: assignmentId
    value: ''
  - key: submissionId
    value: ''
  - key: questionId
    value: ''
  - key: questionId2
    value: ''
  - key: fileId
    value: ''
